# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b193d92f05d0f0d2ec8b4b4c24b5c0408a9e25bb1650dc4afa6199b4cae9ca43b6c44cfefb381888603d8be579da6c3bc65dd3483470b454eece72450fc0d34

test:
  secret_key_base: c5988e01c167c44f9a30b325e6e9b009b64b88c95b8a7bccecccd7a94874687302310bbf73ed2dbb3267c24493343d07affd9694e4a266101d590bb7d148e94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
